### ISSUE TITLE
Outdated namespace in 403 error template

### ISSUE THREAD

**Issue by PascalGentemann** [LM-Commons/LmcRbacMvc#142]
### Bug Report

| Q          | A     |
|------------|-------|
| Version(s) | 4.0.1 |

#### Summary

Namespace is outdated in the 403 error template:

https://github.com/LM-Commons/LmcRbacMvc/blob/85fa90b7cf48eff29c9c7588069e3fcaf56d94ba/view/error/403.phtml#L7-L15

#### Current behavior

Accessing a blocked resource leads to a `Class "LmcRbacMvc\Guard\GuardInterface" not found` error.

#### How to reproduce

Access a blocked resource.

#### Expected behavior

The desired output should look like this:

![image](https://github.com/user-attachments/assets/f60bcfc6-4d43-4c9f-bdb4-252763196f7b)

**Comment by visto9259** [comment]
Thanks @PascalGentemann for reporting this.
I will get to it today.

**Comment by visto9259** [comment]
Fixed in version 4.0.2
Thanks @PascalGentemann for reporting this issue
