### ISSUE TITLE
Replace Interop/Container interface by Psr/Container

### ISSUE THREAD

**Issue by visto9259** [LM-Commons/LmcRbacMvc#28]
Interop/Container is deprecated.  
Replace by Psr/Container

**Comment by ALTAMASH80** [comment]
Hi, I've added a pull request for this enhancement. Thanks!

**Comment by visto9259** [comment]
Hi @ALTAMASH80,

I saw your fork with the changes.  Did you create a pull request against this repo?  I don't see it.

**Comment by ALTAMASH80** [comment]
Hi @visto9259, just created a pull request here. #30

**Comment by visto9259** [comment]
Released in v3.3.1
